CREATE DATABASE IF NOT EXISTS opcat ; 

ALTER DATABASE opcat CHARACTER SET = 'utf8'

USE opcat ; 

CREATE USER IF NOT EXISTS 'opcat' IDENTIFIED BY '0545224014';

GRANT  ALL PRIVILEGES ON opcat.* TO 'opcat'@'%' ; 


